ensure -o argument value is valid
your outlineFormatKeys is supposed to contain tuples, a single item tuple still needs a comma at the end, otherwise the parentheses are ignored, you do *outlineFormatKey later on which basically unpacks the string itself into its individual characters, instead of upacking the tuple that contains the string...

without this fix, I get:
error: argument -o/--output: invalid choice

and I can see in the __arguments list printed in the Macro panel that it tries to pass '-o', 'v', 'a', 'r', 'i', 'a', 'b', 'l', 'e'